surrealdb/www.surrealdb.com

- app/templates/docs/integration/libraries/javascript.hbs
The description for db.let function was the same as db.use
> Fix description for db.let function in js docs

- app/templates/docs/surrealql/datamodel/casting.hbs
In the casting section of the docs, The description for casting strings  describe casting for decimal values instead of string.
> Fix string cast description

- app/templates/docs/integration/libraries/deno.hbs
Command wasn't correct:
```
$ deno --allow-net=127.0.0.1:8000 mod.ts
error: Found argument '--allow-net' which wasn't expected, or isn't valid in this context
If you tried to supply `--allow-net` as a value rather than a flag, use `-- --allow-net`
USAGE:
deno [OPTIONS] [SUBCOMMAND]
For more information try --help
````
It should be:
```
$ deno run --allow-net=127.0.0.1:8000 mod.ts 
```
> Fix deno run command

- app/templates/docs/surrealql/operators.hbs
This pr adds four additional description boxes on the https://surrealdb.com/docs/surrealql/operators page, for the fuzzy matching operators. I don't have much experience with ember/handlebars, but I have tried to replicate the structure in the rest of the page.
> Add match examples

- app/templates/docs/integration/http.hbs
Using the example command as previously written does not work. As far as I can tell this would be correct documentation, but not fully sure. I do know the curl command works now though.
> Replaced "Content-Type" in API docs with "Accept"

- app/snippets/docs/integration/libraries/deno/basic.js
The current code is three versions out of date. We can simply choose to not pin the version to make sure we do not need to update this every time the library is updated. I've also removed strange and unnecessary spaces.
> docs: update deno example code to be evergreen

- Makefile
Adding npx explicitly to start ember serve (in case global install failed/terminal hasnt reloaded)
> Add explicit npx to run ember

- app/templates/docs/surrealql/functions/count.hbs
Correcting an outdated string that was referring to the statment for grouping all rows in one as "group by all" instead of the method "group all", of the new version.
> Correct `GROUP BY` -> `GROUP` clause for `count()` docs

- app/snippets/docs/integration/libraries/nodejs/basic.js
Method substr is deprecated now. I replaced it on its equivalent - slice. Their execution result is the same
Math.random().toString(36).substr(2, 10); // '7u98ksx1u8'
Math.random().toString(36).slice(2, 12); //  'wp1lnmupfa'
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr
> Replace deprecated method

- app/templates/docs/integration/libraries/java.hbs
Removing 2 params that we dont want in the API and are making the layout too large
> Remove redundant params in java docs

- app/templates/docs/surrealql/functions/time.hbs
Addresses https://github.com/surrealdb/surrealdb/issues/1973
> Docs - Correct semantics of the time::round function.

- app/styles/components/header.scss
This PR keeps the header in view while scrolling through the content on all pages. Allowing users to navigate better and have access to more nav options without scrolling to the top of the page. 
Before:
After:
> Make header sticky on website

- app/snippets/docs/surrealql/statements/select/expr.surql
- app/snippets/docs/surrealql/statements/select/where.surql
Add an example of using graph edge property filtering.
Query test:
```
test/test> create post content {details: 'blaaaa'}
[{ details: 'blaaaa', id: post:bo0weixeus9cibogw1w0 }]
test/test> relate person:one->reaction->post:bo0weixeus9cibogw1w0 content {type: 'celebrate'}
[{ id: reaction:izzaunzjrxqnyybpob4v, in: person:one, out: post:bo0weixeus9cibogw1w0, type: 'celebrate' }]
test/test> SELECT * FROM person WHERE ->(reaction WHERE type='celebrate')->post
[{ id: person:one, name: 'one' }]
```
> Add exmaples of filtering based on graph edge properties

- app/snippets/docs/integration/libraries/golang/unmarshal.go
Sample code from "_app/snippets/docs/libraries/golang/unmarshall.go_ " has been updated due to variable name mismatch
UserData variable was not defined!
> docs: updated sample code

- app/templates/docs/installation/windows.hbs
Updated windows.hbs to remove "C:\Program Files" path from commands and use the surreal command which works fine on Windows.
> Corrected Windows Installation Instructions

- app/components/footer/index.hbs
Closes #227 
Added the correct icon to the medium link. Change from `fa-dev` to `fa-medium`
> fix: medium icon on homepage

- app/snippets/docs/surrealql/statements/define/field/array-assert-field.surql
- app/snippets/docs/surrealql/statements/select/group.surql
- app/templates/docs/integration/websocket/text.hbs
Some minor fixes
Before
After
Before
After
Link corrected as external link to YouTube
> Correct syntax, fix syntax highlighting, and link

- app/templates/docs/surrealql/functions/index.hbs
Just a simple typo fix I found on the website while reading
You can see the typo [here](https://surrealdb.com/docs/surrealql/functions) in the `Sleep function` section, it says `paysing` instead of `pausing`
> Fix typo `paysing`

- app/snippets/docs/integration/libraries/rust/delete.rust
Should be Option<T>, was Vec<T>, which would throw an error. The documentation is correct on [docs.rs](https://docs.rs/surrealdb/1.0.0-beta.9+20230402/surrealdb/struct.Surreal.html#method.delete)
> Fixed the Rust doc return type of deleting a specific record from a table

- app/styles/links.scss
Links do not currently have focus styling which causes A11Y issues regarding keyboard navigations.
> WWW: Add focus for focusable elements

- app/components/section/releases/index.js
- app/components/section/releases/v1-0-0-beta-10.hbs
- app/snippets/docs/embedding/libraries/rust/cargo-features.bash
- app/snippets/docs/surrealql/statements/define/namespace/namespace.surql
- app/snippets/docs/surrealql/statements/for/syntax.typescript
- app/templates/docs/cli/backup.hbs
- app/templates/docs/cli/index.hbs
- app/templates/docs/installation/upgrading/beta9-to-beta10.hbs
- app/templates/docs/integration/websocket/text.hbs
- app/templates/docs/surrealql/demo.hbs
- app/templates/docs/surrealql/functions/array.hbs
- app/templates/docs/surrealql/functions/string.hbs
- app/templates/docs/surrealql/operators.hbs
- app/templates/docs/surrealql/statements/delete.hbs
- app/templates/docs/surrealql/statements/relate.hbs
- app/templates/docs/surrealql/statements/select.hbs
- app/templates/docs/surrealql/statements/show.hbs
- app/templates/team.hbs
- temp.md
Typos were found using [crate-ci/typos](https://github.com/crate-ci/typos); however, there are too many false flags to be reasonably integrated into the site.
> fix: typos

- app/templates/docs/surrealql/functions/array.hbs
Hi, I've spotted this tiny mistake in the website about array::transpose
> fix: API definition of array::transpose
