app/templates/docs/integration/http.hbs

Fix wrong header name Authorisation. https://github.com/surrealdb/surrealdb/issues/134

Fix typo on http rest api header

---

app/templates/features.hbs

Fix typo in features/client-libraries

---

app/templates/docs/surrealql/statements/index.hbs

The statements index page had incorrect descriptions. I've tried to correct it.

Tried to make statement descriptions more accurate

---

app/snippets/docs/start/index/step1.bash
app/snippets/docs/start/index/step2.bash
app/snippets/docs/start/index/step3.bash
app/snippets/docs/start/index/step4.bash
app/snippets/docs/start/index/step5.bash
app/snippets/docs/start/index/step6.bash
app/snippets/docs/start/index/step7.bash
app/snippets/docs/start/index/step8.bash

Update to Beta8 requires these examples changes

Changed Examples in Docs

---

app/snippets/features/permissions/scope.js

Hi @tobiemh, this pr fixes the examples missed in #47.

Changed Header in features/permissions

---

app/templates/docs/surrealql/functions/string.hbs

Fixed `concat` and `join` descriptions.

Fix Copy/Paste errors

---

app/templates/docs/index.hbs

Add visually prominent link from SurrealDB docs to SurrealQL docs.

add cross link to SurrealQL

---

app/snippets/docs/surrealql/overview/record-numeric.sql

Corrected spelling of 'celsius'

---

.gitignore

Adding idea to gitignore for all the WebStorm/IntelliJ folks

Add idea to gitignore

---

app/router.js
app/snippets/docs/surrealql/statements/sleep/main.sql
app/snippets/docs/surrealql/statements/sleep/syntax.typescript
app/templates/docs.hbs
app/templates/docs/surrealql/functions/index.hbs
app/templates/docs/surrealql/functions/sleep.hbs
app/templates/docs/surrealql/statements/index.hbs
app/templates/docs/surrealql/statements/sleep.hbs

Document the function and statement introduced by https://github.com/surrealdb/surrealdb/pull/1674

Documents Sleep function and Sleep statement

---

app/snippets/docs/integration/libraries/golang/modify.go
app/snippets/docs/integration/libraries/golang/unmarshal_raw.go

Updated modify.go

---

app/templates/docs.hbs
app/templates/docs/deployment/index.hbs

Add available tag to Fly.io and update the listing order under deployment

Docs: Add available tag to fly.io

---

app/snippets/docs/surrealql/statements/insert/batch.surql
app/templates/docs/surrealql/statements/insert.hbs

Add documentation for batch inserting values.

Add batch insert docs

---

app/templates/docs/integration/libraries/python.hbs

there is no method ".modify()"  it's called ".patch()"

docs-python.hbs-wrong-method-name

---

app/templates/docs/faqs.hbs
app/templates/docs/introduction/questions.hbs

Add release notes and roadmap links to frequently asked questions page

Add release notes and roadmap links to faq

---

app/styles/components/layout/helm.scss

My PR yesterday broke scroll on blogpost and docs menu. This PR fixes that.

fix scroll for blog page and docs menus

---

app/templates/docs/guides/authenticating-users.hbs
app/templates/docs/guides/computed-views.hbs
app/templates/docs/guides/data-triggers.hbs
app/templates/docs/guides/deploying-surrealdb.hbs
app/templates/docs/guides/geospatial-functionality.hbs
app/templates/docs/guides/index.hbs
app/templates/docs/guides/realtime-subscriptions.hbs
app/templates/docs/guides/relations-and-graph.hbs
app/templates/docs/guides/schemafull-or-schemaless.hbs
app/templates/docs/guides/strict-mode.hbs

Making good on the promise of removing lorem ipsum and instead having coming soon.
https://discord.com/channels/902568124350599239/902568124350599242/1115564570740801617

Removing lorem ipsum; adding coming soon

---

app/templates/docs/introduction/start.hbs

This changes some parts of the documentation that sounded off upon reading.

refactor(docs): minor "getting started" page enhancements

---

app/snippets/docs/surrealql/statements/select/timeout.surql
app/templates/docs/surrealql/statements/update.hbs

Fix grammar

---

app/templates/index.hbs

tried to make language sparkle a little more & replaced cloud reference (since it is not here yet) with link to install page.

Home page 2nd para

---

app/snippets/docs/surrealql/statements/select/group.surql

Missing semicolon.
I require no clout or compensation for this considerable effort. ;>

Update group.surql - Missing semicolon

---

app/snippets/docs/cli/help/sql.txt
app/templates/docs/cli/sql.hbs

CLI SQL command documentation updates for the new beta 10 changes.
Issue where it came up:
https://github.com/surrealdb/surrealdb/issues/2598

CLI SQL command documentation updates for beta 10.

---

app/templates/docs/surrealql/datamodel/objects.hbs

fix: typo corrected (documentation)

---

app/snippets/docs/surrealql/statements/ifelse/nested.surql
app/templates/docs/surrealql/statements/ifelse.hbs

Docs: Add nested if else example
